apiVersion: v1
kind: ConfigMap
metadata:
  name: user-app-config
  namespace: user-app
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "user_app_db"
  JWT_EXPIRATION: "24h"
  JWT_REFRESH_EXPIRATION: "168h"
