apiVersion: v1
data:
  000000_enable_postgis.down.sql: |
    -- Disable PostGIS extension
    DROP EXTENSION IF EXISTS postgis;
  000000_enable_postgis.up.sql: |
    -- Enable PostGIS extension
    CREATE EXTENSION IF NOT EXISTS postgis;
  000001_create_users_table.down.sql: |
    -- Drop users table
    DROP TABLE IF EXISTS users;
  000001_create_users_table.up.sql: |
    CREATE TABLE users (
        id UUID PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX idx_users_email ON users (email);
  000002_add_password_to_users.down.sql: |
    ALTER TABLE users DROP COLUMN password;
  000002_add_password_to_users.up.sql: |
    ALTER TABLE users ADD COLUMN password VARCHAR(255) NOT NULL DEFAULT '';
kind: ConfigMap
metadata:
  name: migration-files
  namespace: user-app
